name       : perl-config-general
version    : '2.65'
release    : 7
homepage   : https://metacpan.org/pod/Config::General
source     :
    - https://search.cpan.org/CPAN/authors/id/T/TL/TLINDEN/Config-General-2.65.tar.gz : 4d6d5754be3a9f30906836f0cc10e554c8832e14e7a1341efb15b05d706fc58f
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl Generic Config Module
description: |
    This module opens a config file and parses its contents for you. The new method requires one parameter which needs to be a filename. The method getall returns a hash which contains all options and its associated values of your config file. The format of config files supported by Config::General is inspired by the well known Apache config format, in fact, this module is 100% compatible to Apache configs, but you can also just use simple name/value pairs in your config files. In addition to the capabilities of an Apache config file it supports some enhancements such as here-documents, C-style comments or multiline options.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
